=== jariba/europa-pso/PLASMA/trunk/CBPlanner/component/Heuristics-HSTS.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="HSTS"
xmlns="HSTS" elementFormDefault="qualified">
<xs:element name="Heuristics-HSTS">
<xs:complexType> 
<xs:all>

<xs:element name="Defaults" maxOccurs="1" minOccurs="1">
    <xs:complexType>
      <xs:all>
      <xs:element name="Priority" type="xs:string"/>
      <xs:element name="Compatibility">
          <xs:complexType>
	  <xs:all>
	    <xs:element name="MasterList">
	      <xs:complexType>
              <xs:sequence>
                  <xs:element name="PredicateName" type="xs:string"/>
                  <xs:element name="ValueList">
		      <xs:complexType>
		      <xs:sequence minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Value" type="xs:string"/>
		      </xs:sequence>
                      </xs:complexType>
                  </xs:element>
              </xs:sequence>
	      </xs:complexType>
            </xs:element>
	    </xs:all>
          </xs:complexType>
      </xs:element>
      <xs:element name="Token">
          <xs:complexType>
	  <xs:all>
	   <xs:element name="Priority" type="xs:decimal" default="100000.0"/>
           <xs:element name="DecisionPreference">
               <xs:complexType>
	         <xs:all>
                 <xs:element name="State" type="xs:string"/>
                 <xs:element name="Order" type="xs:string"/>
		 </xs:all>
               </xs:complexType>
           </xs:element>
 	  </xs:all>
          </xs:complexType>
      </xs:element>
      <xs:element name="ConstrainedVariable">
          <xs:complexType>
	    <xs:all>
	    <xs:element name="Priority" type="xs:decimal" default="100000.0"/>
	    <xs:element name="ValueOrder" type="xs:string"/>
	    </xs:all>
          </xs:complexType>
      </xs:element>
     </xs:all>
    </xs:complexType>
</xs:element>

<xs:element name="VariableSpecification">
<xs:complexType>
<xs:sequence minOccurs="0" maxOccurs="unbounded">
<xs:element name="ConstrainedVariable">
    <xs:complexType>
    <xs:sequence>
      <xs:element name="Priority" type="xs:decimal"/>
      <xs:element name="Preference">
      <xs:complexType>
      <xs:choice>
          <xs:element name="ValueOrder" type="xs:string"/>
          <xs:element name="Generator" type="xs:string"/>
          <xs:element name="DomainOrder">
            <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="DomainValue" type="xs:string"/>
            </xs:sequence>
            </xs:complexType>
          </xs:element>
      </xs:choice>
      </xs:complexType>
      </xs:element>
      <xs:element name="Variable">
      <xs:complexType>
      <xs:choice>
          <xs:element name="Index" type="xs:integer"/>
          <xs:element name="Name" type="xs:string"/> 
      </xs:choice>
      </xs:complexType>
      </xs:element>
      <xs:element name="PredicateName" type="xs:string"/>  
      <xs:element name="ValueList">
          <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:element name="Value" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
      </xs:element>
    </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>

<xs:element name="TokenSpecification">
<xs:complexType>
<xs:sequence minOccurs="0" maxOccurs="unbounded">
<xs:element name="Token">
<!-- predicate (pred,vars), subgoal relation, master (pred, vars), state, order -->
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>


</xs:all>
</xs:complexType> 
</xs:element>
</xs:schema>

=== jariba/europa-pso/PLASMA/trunk/CBPlanner/component/Heuristics-HSTS.xml
<?xml version="1.0"?>

<Heuristics-HSTS
xmlns="HSTS"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="Heuristics-HSTS.xsd">

<Defaults>
 <Priority>low</Priority>
 <Compatibility>
   <MasterList>
     <PredicateName>Max_ThrustTime</PredicateName>
     <ValueList/>
   </MasterList>
 </Compatibility>
 <Token>
   <Priority>10000.0</Priority>
   <DecisionPreference>
     <State>merge</State>
     <Order>early</Order>
   </DecisionPreference>
 </Token>
 <ConstrainedVariable>
   <Priority>5000.0</Priority>
   <ValueOrder>ascending</ValueOrder>
 </ConstrainedVariable> 
</Defaults>

<VariableSpecification>
<ConstrainedVariable>
  <Priority>6000.5</Priority>
  <Preference>
  <ValueOrder>descending</ValueOrder>
  </Preference>
  <Variable>
    <Index>2</Index>
  </Variable>
  <PredicateName>Rover.Arm.Extend</PredicateName>
  <ValueList/>
</ConstrainedVariable>

<ConstrainedVariable>
  <Priority>6000.25</Priority>
  <Preference>
  <Generator>MyCVGenerator</Generator>
  </Preference>
  <Variable>
    <Name>WillNavNext</Name>
  </Variable>
  <PredicateName>Rover.Navigate</PredicateName>
  <ValueList>
     <Value/>
     <Value>Target524</Value>
  </ValueList>
</ConstrainedVariable>

<ConstrainedVariable>
  <Priority>6000.25</Priority>
  <Preference>
  <DomainOrder>
    <DomainValue>OBS_INACTIVE_MEETS_OPNAV</DomainValue>
    <DomainValue>OBS_INACTIVE_MEETS_INACTIVE_BOUNDARY</DomainValue>
    <DomainValue>OBS_INACTIVE_MEETS_INACTIVE_INACTIVE</DomainValue>
  </DomainOrder>
  </Preference>
  <Variable>
    <Index>10</Index>
  </Variable>
  <PredicateName>Obs_Window_Inactive</PredicateName>
  <ValueList>
     <Value/>
     <Value/>
     <Value/>
     <Value>STANDBY</Value>
  </ValueList>
</ConstrainedVariable>
</VariableSpecification>

<TokenSpecification/>

</Heuristics-HSTS>

<!-- possible values: reject,merge,defer,activate -->
<!-- when merge or activate is specified, it is possible to specify
ActiveToken or SuccessorToken preference criteria with possible values: 
close,far,early,late,maxFlexible,minFlexible,leastSpecifiedToken,mostSpecifiedToken,leastSpecifiedObject,mostSpecifiedObject
or a <Generator></Generator> tag -->
