=== jariba/europa-pso/PlanWorks/branches/import/xml/test/PlanDb.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : PlanDb.dtd
    Created on : March 30, 2003, 3:52 PM
    Author     : Conor McGann
    Description:
        Specify format for representing all state in the plan database.
-->

<!--
	15/04/2003: Added Decision element to Partial Plan. -MJI/WMT
-->

<!--
	18/04/2003: Removed Decision element.  It is apparently
	unnecessary and was malformed anyway.  Added Predicate type. -MJI
-->
<!--
	22/04/2003: Added Predicate and Parameter types.  Variable now has paramId attribute.
	Token now has predicateId attribute. -MJI
-->
<!--
	25/04/2003: Added name attribute to Constraint.	-MJI
-->
<!--
        28/04/2003: Added TokenRelation* & Parameter* to PartialPlan element;
                     EnumeratedDomain (CDATA+) => EnumeratedDomain (#PCDATA). - WMT
-->
<!--
        02/05/2003: Removed Parameter* from PartialPlan element;
                      Parameter is a sub-element of Predicate - WMT
-->


<!-- !ELEMENT PartialPlan (Token*, Object*, Variable*, Constraint*, Predicate*) -->
<!ELEMENT PartialPlan (Token*, Object*, Variable*, Constraint*, TokenRelation*, Predicate*)>
<!ATTLIST PartialPlan key ID #REQUIRED>
<!ATTLIST PartialPlan model CDATA #REQUIRED>

<!ELEMENT Token EMPTY>
<!ATTLIST Token key ID #REQUIRED>
<!ATTLIST Token isValueToken (Y | N) "Y">
<!ATTLIST Token predicateId IDREF #REQUIRED>
<!ATTLIST Token startVarId IDREF #REQUIRED>
<!ATTLIST Token endVarId IDREF #REQUIRED>
<!ATTLIST Token durationVarId IDREF #REQUIRED>
<!ATTLIST Token objectVarId IDREF #REQUIRED>
<!ATTLIST Token rejectVarId IDREF #REQUIRED>
<!ATTLIST Token tokenRelationIds IDREFS "">
<!ATTLIST Token paramVarIds IDREFS "">
<!ATTLIST Token slotId IDREF #IMPLIED>

<!ELEMENT Object (Timeline+)>
<!ATTLIST Object key ID #REQUIRED>
<!ATTLIST Object name CDATA #REQUIRED>

<!ELEMENT Timeline (Slot+)>
<!ATTLIST Timeline key ID #REQUIRED>
<!ATTLIST Timeline name CDATA #REQUIRED>

<!ELEMENT Slot (Token*)>
<!ATTLIST Slot key ID #REQUIRED>

<!ELEMENT TokenRelation EMPTY>
<!ATTLIST TokenRelation key ID #REQUIRED>
<!ATTLIST TokenRelation masterToken IDREF #REQUIRED>
<!ATTLIST TokenRelation slaveToken IDREF #REQUIRED>

<!ELEMENT Variable (IntervalDomain | EnumeratedDomain)>
<!ATTLIST Variable key ID #REQUIRED>
<!ATTLIST Variable type (START_VAR | END_VAR | DURATION_VAR | OBJECT_VAR | REJECT_VAR | PARAMETER_VAR)  #REQUIRED>
<!ATTLIST Variable constraintIds IDREFS #IMPLIED>
<!ATTLIST Variable paramId IDREF #REQUIRED>

<!ELEMENT IntervalDomain EMPTY>
<!ATTLIST IntervalDomain type (INTEGER_SORT | REAL_SORT) #REQUIRED>
<!ATTLIST IntervalDomain lowerBound CDATA #REQUIRED>
<!ATTLIST IntervalDomain upperBound CDATA #REQUIRED>

<!-- !ELEMENT EnumeratedDomain (CDATA+) -->
<!ELEMENT EnumeratedDomain (#PCDATA)>

<!ELEMENT Constraint EMPTY>
<!ATTLIST Constraint key ID #REQUIRED>
<!ATTLIST Constraint name CDATA #REQUIRED>
<!ATTLIST Constraint type (TEMPORAL | ATEMPORAL) #REQUIRED>
<!ATTLIST Constraint variableIds IDREFS #REQUIRED>

<!ELEMENT Predicate (Parameter*)>
<!ATTLIST Predicate key ID #REQUIRED>
<!ATTLIST Predicate name CDATA #REQUIRED>

<!ELEMENT Parameter EMPTY>
<!ATTLIST Parameter key ID #REQUIRED>
<!ATTLIST Parameter name CDATA #REQUIRED>

=== jariba/europa-pso/PlanWorks/trunk/xml/test/monkey/step0000.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PartialPlan SYSTEM '../../dtd/PlanDb.dtd'>

<PartialPlan key="K1" model="monkey.ddl">
	<Object key="K2" name="Monkey1">
		<Timeline key="K3" name="LOCATION_SV">
			<Slot key="K6">
<!--AT{ROCK}-->
				<Token key="K19" isValueToken="Y" predicateId="K32" startVarId="K55" endVarId="K56" durationVarId="K102" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K97" paramVarIds="K81" slotId="K6" />
			</Slot>
			<Slot key="K7">
<!--GOING{ROCK, TREE}-->
				<Token key="K20" isValueToken="Y" predicateId="K33" startVarId="K57" endVarId="K58" durationVarId="K103" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K96 K97 K98" paramVarIds="K81 K82" slotId="K7" />
			</Slot>
			<Slot key="K8">
<!--AT{TREE}-->
				<Token key="K21" isValueToken="Y" predicateId="K32" startVarId="K59" endVarId="K60" durationVarId="K102" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K94 K96" paramVarIds="K82" slotId="K8" />
				<Token key="K120" isValueToken="Y" predicateId="K32" startVarId="K59" endVarId="K60" durationVarId="K102" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K90" paramVarIds="K82" slotId="K8" />
				<Token key="K121" isValueToken="Y" predicateId="K32" startVarId="K59" endVarId="K60" durationVarId="K102" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K88" paramVarIds="K82" slotId="K8" />
			</Slot>
			<Slot key="K9">
<!--GOING{TREE, ROCK}-->
				<Token key="K22" isValueToken="Y" predicateId="K33" startVarId="K61" endVarId="K62" durationVarId="K103" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K89 K90 K91" paramVarIds="K82 K81" slotId="K9" />
			</Slot>
			<Slot key="K10">
<!--AT{ROCK}-->
				<Token key="K23" isValueToken="Y" predicateId="K32" startVarId="K63" endVarId="K64" durationVarId="K102" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K89" paramVarIds="K81" slotId="K10" />
			</Slot>
		</Timeline>
		<Timeline key="K4" name="ALTITUDE_SV">
			<Slot key="K11">
<!--LOW-->
				<Token key="K24" isValueToken="Y" predicateId="K34" startVarId="K65" endVarId="K66" durationVarId="K-1" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K87" paramVarIds="K-2" slotId="K11" />
				<Token key="K122" isValueToken="Y" predicateId="K34" startVarId="K65" endVarId="K66" durationVarId="K-1" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K98" paramVarIds="K-2" slotId="K11" />
			</Slot>
			<Slot key="K12">
<!--CLIMBING-->
				<Token key="K25" isValueToken="Y" predicateId="K36" startVarId="K67" endVarId="K68" durationVarId="K106" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K86 K87 K88" paramVarIds="K-2" slotId="K12" />
			</Slot>
			<Slot key="K13">
<!--HIGH-->
				<Token key="K26" isValueToken="Y" predicateId="K35" startVarId="K69" endVarId="K70" durationVarId="K104" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K85 K86" paramVarIds="K-2" slotId="K13" />
				<Token key="K123" isValueToken="Y" predicateId="K35" startVarId="K69" endVarId="K70" durationVarId="K104" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K95" paramVarIds="K-2" slotId="K13" />
			</Slot>
			<Slot key="K14">
<!--CLIMBING_DOWN-->
				<Token key="K27" isValueToken="Y" predicateId="K37" startVarId="K71" endVarId="K72" durationVarId="K107" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K84 K85" paramVarIds="K-2" slotId="K14" />
			</Slot>
			<Slot key="K15">
<!--LOW-->
				<Token key="K28" isValueToken="Y" predicateId="K34" startVarId="K73" endVarId="K74" durationVarId="K105" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K84 K91" paramVarIds="K-2" slotId="K15" />
			</Slot>
		</Timeline>
		<Timeline key="K5" name="BANANA_SV">
			<Slot key="K16">
<!--NOT_HAVE_BANANA-->
				<Token key="K29" isValueToken="Y" predicateId="K39" startVarId="K75" endVarId="K76" durationVarId="K99" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K93" paramVarIds="K-2" slotId="K16" />
			</Slot>
			<Slot key="K17">
<!--GRABBING_BANANA-->
				<Token key="K30" isValueToken="Y" predicateId="K41" startVarId="K77" endVarId="K78" durationVarId="K101" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K92 K93 K94 K95" paramVarIds="K-2" slotId="K17" />
			</Slot>
			<Slot key="K18">
<!--HAVE_BANANA-->
				<Token key="K31" isValueToken="Y" predicateId="K40" startVarId="K79" endVarId="K80" durationVarId="K100" objectVarId="K2" rejectVarId="K83" tokenRelationIds="K92" paramVarIds="K-2" slotId="K18" />
			</Slot>
		</Timeline>
	</Object>
<!--AT(ROCK) START-->
	<Variable key="K55" type="START_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[0]]></EnumeratedDomain>
	</Variable>
<!--AT(ROCK) END-->
	<Variable key="K56" type="END_VAR" constraintIds="K108" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="1" upperBound="177" />
	</Variable>
<!--GOING(ROCK,TREE) START-->
	<Variable key="K57" type="START_VAR" constraintIds="K108" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="1" upperBound="177" />
	</Variable>
<!--GOING(ROCK,TREE) END-->
	<Variable key="K58" type="END_VAR" constraintIds="K109" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="6" upperBound="182" />
	</Variable>
<!--AT(TREE) START-->
	<Variable key="K59" type="START_VAR" constraintIds="K109" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="6" upperBound="182" />
	</Variable>
<!--AT(TREE) END-->
	<Variable key="K60" type="END_VAR" constraintIds="K110" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="18" upperBound="194" />
	</Variable>
<!--GOING(TREE,ROCK) START-->
	<Variable key="K61" type="START_VAR" constraintIds="K110" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="18" upperBound="194" />
	</Variable>
<!--GOING(TREE,ROCK) END-->
	<Variable key="K62" type="END_VAR" constraintIds="K111" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="23" upperBound="199" />
	</Variable>
<!--AT(ROCK) START-->
	<Variable key="K63" type="START_VAR" constraintIds="K111" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="23" upperBound="199" />
	</Variable>
<!--AT(ROCK) END-->
	<Variable key="K64" type="END_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[200]]></EnumeratedDomain>
	</Variable>
<!--LOW START-->
	<Variable key="K65" type="START_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[0]]></EnumeratedDomain>
	</Variable>
<!--LOW END-->
	<Variable key="K66" type="END_VAR" constraintIds="K112" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="6" upperBound="182" />
	</Variable>
<!--CLIMBING START-->
	<Variable key="K67" type="START_VAR" constraintIds="K112" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="6" upperBound="182" />
	</Variable>
<!--CLIMBING END-->
	<Variable key="K68" type="END_VAR" constraintIds="K113" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="16" upperBound="192" />
	</Variable>
<!--HIGH START-->
	<Variable key="K69" type="START_VAR" constraintIds="K113" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="16" upperBound="192" />
	</Variable>
<!--HIGH END-->
	<Variable key="K70" type="END_VAR" constraintIds="K114" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="17" upperBound="193" />
	</Variable>
<!--CLIMBING_DOWN START-->
	<Variable key="K71" type="START_VAR" constraintIds="K114" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="17" upperBound="193" />
	</Variable>
<!--CLIMBING_DOWN END-->
	<Variable key="K72" type="END_VAR" constraintIds="K115" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="18" upperBound="194" />
	</Variable>
<!--LOW START-->
	<Variable key="K73" type="START_VAR" constraintIds="K115" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="18" upperBound="194" />
	</Variable>
<!--LOW END-->
	<Variable key="K74" type="END_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[200]]></EnumeratedDomain>
	</Variable>
<!--NOT_HAVE_BANANA START-->
	<Variable key="K75" type="START_VAR" constraintIds="K-2" paramId="K-2">
		<EnumeratedDomain><![CDATA[0]]></EnumeratedDomain>
	</Variable>
<!--NOT_HAVE_BANANA END-->
	<Variable key="K76" type="END_VAR" constraintIds="K116" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="16" upperBound="192" />
	</Variable>
<!--GRABBING_BANANA START-->
	<Variable key="K77" type="START_VAR" constraintIds="K116" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="16" upperBound="192" />
	</Variable>
<!--GRABBING_BANANA END-->
	<Variable key="K78" type="END_VAR" constraintIds="K117" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="17" upperBound="193" />
	</Variable>
<!--HAVE_BANANA START-->
	<Variable key="K79" type="START_VAR" constraintIds="K117" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="17" upperBound="193" />
	</Variable>
<!--HAVE_BANANA END-->
	<Variable key="K80" type="START_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[200]]></EnumeratedDomain>
	</Variable>
	<Variable key="K81" type="PARAMETER_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[ROCK]]></EnumeratedDomain>
	</Variable>
	<Variable key="K82" type="PARAMETER_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[TREE]]></EnumeratedDomain>
	</Variable>
	<Variable key="K83" type="REJECT_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[True]]></EnumeratedDomain>
	</Variable>
	<Variable key="K99" type="DURATION_VAR" constraintIds="K-2" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="1" upperBound="_plus_infinity_"/>
	</Variable>
	<Variable key="K100" type="DURATION_VAR" constraintIds="K-1" paramId="K-2">
		<IntervalDomain type="INTEGER_SORT" lowerBound="1" upperBound="_plus_infinity_"/>
	</Variable>
	<Variable key="K101" type="DURATION_VAR" constraintIds="K-1" paramId="K-2">
		<EnumeratedDomain><![CDATA[1 2]]></EnumeratedDomain>
	</Variable>
